try:  
    a=10/5;  
    print("Exception occurred")  
finally:  
    print(a)  
